let level = {
        blocks: [
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'start', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'empty', is_block: false},
                {type: 'finish', is_block: false},
                {type: 'empty', is_block: false},
            ],
            [
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
                {type: 'brick', is_block: true},
            ],
        ],
        startPosition: {x: 4, y: 4},
        startFromBottom: true,
        speedX: 15,
        theme: 'default',
    }
