export default {
    BLOCK_WIDTH: 36,
    BLOCK_HEIGHT: 24,
    HERO_WIDTH: 36,
    HERO_HEIGHT: 24,
    HERO_PADDING_X: 36,
    HERO_PADDING_Y: 48,
    CAMERA_PADDING_X: 150,
    CAMERA_PADDING_Y: 150,
    TICK: 50,
};